platform: linux
image_resource:
  type: docker-image
inputs:
  - name: pxf_src
  - name: cluster_env_files
  - name: bin_gpdb
  - name: pxf_tarball
params:
  GROUP: feature
  TARGET_OS: centos
  TARGET_OS_VERSION: 6
run:
  ADL_ACCOUNT:
  ADL_CLIENT_ID:
  ADL_CREDENTIAL:
  ADL_REFRESH_URL:
  AWS_DEFAULT_REGION:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  BENCHMARK_ADL: false
  BENCHMARK_GCS: false
  BENCHMARK_GPHDFS: false
  BENCHMARK_S3: false
  BENCHMARK_WASB: false
  GOOGLE_CREDENTIALS:
  path: pxf_src/concourse/scripts/test_pxf_multinode.bash
  SCALE:
  TARGET_OS:
  WASB_ACCOUNT_KEY:
  WASB_ACCOUNT_NAME:
